/* TG-02a: telegram_linking_codes table.
 *
 * Stores short-lived one-time codes the desktop app issues so a user can
 * type `/start <code>` in the Telegram bot and link their account. Codes
 * are server-only — they never sync to clients (the code itself is the
 * secret). The table is therefore plain Postgres, no sync trio.
 *
 * Columns:
 *   code         8-char alphanumeric (uppercase, ambiguity-free alphabet),
 *                primary key. Generated by the linking service.
 *   user_id      Issuing user (FK to users; cascades on user delete).
 *   expires_at   Epoch ms past which the code is invalid (15 min TTL).
 *   consumed_at  Epoch ms when the bot redeemed it (NULL = unused).
 *   created_at   Epoch ms when issued.
 *
 * Index on (user_id, created_at) drives the rate-limit query — count
 * active codes per user (consumed_at IS NULL AND expires_at > now()).
 */

/** @param {import('node-pg-migrate').MigrationBuilder} pgm */
exports.up = (pgm) => {
  pgm.createTable("telegram_linking_codes", {
    code: { type: "text", primaryKey: true },
    user_id: {
      type: "uuid",
      notNull: true,
      references: "users(id)",
      onDelete: "CASCADE",
    },
    expires_at: { type: "bigint", notNull: true },
    consumed_at: { type: "bigint", notNull: false },
    created_at: { type: "bigint", notNull: true },
  });
  pgm.createIndex("telegram_linking_codes", ["user_id", "created_at"]);
};

/** @param {import('node-pg-migrate').MigrationBuilder} pgm */
exports.down = (pgm) => {
  pgm.dropTable("telegram_linking_codes");
};
